# Generated by Django 2.1.3 on 2019-01-25 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_colaborador_cargo'),
        ('aluno', '0002_auto_20190122_1730'),
        ('classe', '0002_grupo_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_aula', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='presenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.CharField(choices=[('1', 'Sim'), ('2', 'Nao')], default=2, max_length=1)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='grupo_aula',
            name='livro',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='grupo_aula',
            name='pag_atual',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='grupo_aula',
            name='prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colaborador.colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe.grupo_aula'),
        ),
        migrations.AddField(
            model_name='aula',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.colaborador'),
        ),
    ]
