# Generated by Django 2.1.3 on 2019-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0003_auto_20190125_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='estado',
            field=models.CharField(choices=[('1', 'Agendada'), ('2', 'Lecionada'), ('2', 'Cancelada')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='aula',
            name='presentes',
            field=models.ManyToManyField(to='classe.presenca'),
        ),
    ]
