# Generated by Django 2.1.3 on 2019-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0004_auto_20190125_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='unidade',
            field=models.CharField(choices=[('1', 'Tres Lagoas'), ('2', 'Agua Clara'), ('3', 'Ribas do Rio Pardo'), ('4', 'Campo Grande')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo_aula',
            name='unidade',
            field=models.CharField(choices=[('1', 'Tres Lagoas'), ('2', 'Agua Clara'), ('3', 'Ribas do Rio Pardo'), ('4', 'Campo Grande')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='sala_aula',
            name='unidade',
            field=models.CharField(choices=[('1', 'Tres Lagoas'), ('2', 'Agua Clara'), ('3', 'Ribas do Rio Pardo'), ('4', 'Campo Grande')], default=1, max_length=1),
        ),
    ]
