# Generated by Django 2.1.3 on 2019-01-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0005_auto_20190125_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo_aula',
            name='unidade',
        ),
        migrations.AddField(
            model_name='grupo_aula',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classe.sala_aula'),
            preserve_default=False,
        ),
    ]
