# Generated by Django 2.1.3 on 2019-01-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0006_auto_20190125_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo_aula',
            name='max_alunos',
        ),
    ]
