# Generated by Django 2.1.3 on 2019-01-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0007_remove_grupo_aula_max_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo_aula',
            name='prof',
        ),
    ]
