# Generated by Django 2.1.3 on 2019-01-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0008_remove_grupo_aula_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo_aula',
            name='sala',
        ),
        migrations.AddField(
            model_name='grupo_aula',
            name='unidade',
            field=models.CharField(choices=[('1', 'Tres Lagoas'), ('2', 'Agua Clara'), ('3', 'Ribas do Rio Pardo'), ('4', 'Campo Grande')], default=1, max_length=1),
        ),
    ]
