# Generated by Django 2.1.3 on 2019-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('1', 'Diretor'), ('2', 'Professor'), ('3', 'Recepcionista')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
