# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='aluno',
        ),
    ]
