# Generated by Django 2.1.3 on 2019-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20190122_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default=1, max_length=1),
        ),
    ]
